spring:
  application:
    name: GamingEcommerce
  datasource:
    url: jdbc:mysql://localhost:3306/GamingEcommerce
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true